#! /usr/bin/bash

IP_ADDRESSES=`grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}'  inventory.ini  | sort | uniq`
IFS=" "
arr=($IP_ADDRESSES)
for ip in $arr
do
  ssh-keygen -R "$ip" 2>/dev/null
done
