#! /usr/bin/bash

IPV4_REGEX='[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}'
IP_ADDRESSES=`grep -o ${IPV4_REGEX} inventory.ini | sort | uniq`
IFS=" "
arr=($IP_ADDRESSES)
for ip in $arr
do
  ssh-keygen -R "$ip" 2>/dev/null
done
