#! /usr/bin/bash

vagrant up --provision

# Get dynamically assigned IPs of the VMs
NODE1_IP=`./ip node1`
NODE2_IP=`./ip node2`

# Create inventory for Ansible using dynamically assigned IP addresses
printf "[default]\n%s\n%s\n" $NODE1_IP $NODE2_IP > inventory.ini
printf "\n[node1]\n%s\n" $NODE1_IP >> inventory.ini
printf "\n[node2]\n%s\n" $NODE2_IP >> inventory.ini

ansible-playbook playbook.yml -vvv
