#! /usr/bin/bash

# Given the name of a running vagrant box return its IP addresses for network interface named eth1
# Vagrant is adding 3 network adapter, but the other two seem spurious.
vagrant ssh -c ' ip -f inet addr show eth1' "$1" | sed -En -e 's/.*inet ([0-9.]+).*/\1/p'
