---
- name: Update All VMs
  hosts: default
  become: true
  remote_user: vagrant
  tasks:

    - name: Set authorized key taken from file
      authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', '.ssh/insecure_rsa.pub') }}"

    - name: Avoid vagrant trap with too many keys
      community.general.ini_file:
        path: /etc/ssh/sshd_config
        section:
        option: MaxAuthTries
        value: 50
        backup: yes
    - name: Upgrade all packages
      yum:
        name: '*'
        update_cache: yes
        state: latest
    - name: Install java and packages
      yum:
        name:
          - java-11-openjdk
          - java-11-openjdk-devel
        state: present
        update_cache: yes

- name: Install Reflex
  hosts: reflex
  become: true
  remote_user: vagrant
  tasks:
    - name: DEBUG
      debug:
        msg: "OS {{ ansible_facts['os_family'] }}"

    - name: find
      find:
        paths: /vagrant
        patterns: "*.rpm"
      register: rpm_find

    - name: set fact
      set_fact:
        rpm_file: "{{ rpm_find.files[0].path }}"

    - name: Installing RPM file
      debug: msg="{{ rpm_file }}"

    - name: Install RPM
      yum:
        name: "{{ rpm_file }}"
      become_user: root

    - name: Turn off SSL 1
      lineinfile:
        path: /opt/reflex/etc/reflex.custom.system.properties
        regexp: '(artemis.sslEnabled\s*=\s*).*'
        line: '\1false'

    - name: Turn off SSL 2
      lineinfile:
        path: /opt/reflex/etc/custom.system.properties
        regexp: '(artemis.sslEnabled\s*=\s*).*'
        line: '\1false'

    - name: Turn off SSL 3
      lineinfile:
        path: /opt/reflex/etc/com.connexta.reflex.broker.config.ActiveMQJMSClientFactoryWrapper.config
        regexp: '(.*sslEnabled[\\]+=)(\w+)(.*)'
        line: '\1false\3'

    - name: Update reflex user
      user:
        name: reflex
        groups: syers
        append: yes

    - name: Add sudo to reflex user
      user:
        name: reflex
        groups: wheel
        append: yes
      when: ansible_facts['os_family'] == "RedHat"

    - name: Add sudo to reflex user (deb)
      user:
        name: reflex
        groups: sudo
        append: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Remove reflex password for easy sudo
      shell: "sudo passwd -d reflex"

- name: Install Artemis
  hosts: other
  become: true
  remote_user: vagrant
  tasks:
    - name: Check is artemis already exists
      stat:
        path: "/home/vagrant/artemis/bin/artemis"
      register: artemis_bin

    - name: Set fact
      set_fact:
        artemis_install: "{{ not artemis_bin.stat.exists }}"

    - name: Print msg
      debug:
        msg: "Install Artemis? {{ artemis_install }}"

    - name: Make Artemis destination dir
      file:
        path: /home/vagrant/artemis
        state: directory
      become_user: vagrant
      when: artemis_install

    - name: Extract artemis in home dir
      shell: "tar xf /vagrant/*artemis*.tar.gz -C /home/vagrant/artemis --strip-components 1"
      become_user: vagrant
      when: artemis_install

    - name: Create a symbolic link
      file:
        src: /home/vagrant/artemis/bin/artemis
        dest: /usr/local/bin/artemis
        state: link

    - name: Give the VM time to unzip and sort stuff out. Not sure if sleep should be here, or after creating the sym link.
      pause:
        seconds: 3
      when: artemis_install

    - name: Check is broker already exists
      stat:
        path: "/home/vagrant/reflexer"
      register: broker_dir

    - name: Set broker fact
      set_fact:
        create_broker: "{{ not broker_dir.stat.exists }}"

    - name: Create broker
      shell: >
        /usr/local/bin/artemis create reflexer
        --user admin
        --password admin
        --port-offset 0
        --host 0.0.0.0
        --role amq
        --allow-anonymous
        --addresses wps.v1.result,unicorn.v1.observation
        --no-hornetq-acceptor
        --no-mqtt-acceptor
        --no-stomp-acceptor
        --no-amqp-acceptor
        --verbose
        --force
      args:
        chdir: /home/vagrant
      become_user: vagrant
      when: create_broker

    - name: Create systemd service file for broker "reflexer"
      copy:
        dest: "/etc/systemd/system/artemis.service"
        content: |
          [Unit]
          Description=Artemis Server
          After=network.target
          [Service]
          Type=simple
          Restart=always
          RestartSec=30
          User=vagrant
          ExecStart=/home/vagrant/reflexer/bin/artemis run
          ExecStop=/home/vagrant/reflexer/bin/artemis stop

    - name: Enable/Start Artemis service
      systemd:
        name: artemis
        enabled: yes
        state: started
      register: service_status

    - name: Service status
      debug:
        msg: "Artemis service status is {{ service_status.state }}"

    - name: Live Producer
      copy:
        mode: 0755
        dest: /usr/local/bin/prodlive
        content: |
          #! /usr/bin/bash
          artemis producer \
          --destination 'topic://wps.v1.result' \
          --message-count 99999999 \
          --url 'tcp://10.5.0.3:5672' \
          --user admin \
          --password admin \
          --sleep 2000 \
          --message-size 32 \
          --non-persistent \
          --verbose

    - name: Other Producer
      copy:
        dest: /usr/local/bin/prodother
        mode: 0755
        content: |
          #! /usr/bin/bash
          artemis producer \
          --destination 'topic://wps.v1.result' \
          --default-port 5672
          --message-count 99999999 \
          --url 'tcp://10.5.0.7:61616' \
          --user admin \
          --password admin \
          --sleep 2000 \
          --message-size 32 \
          --verbose

    - name: Other Consumer
      copy:
        dest: /usr/local/bin/conother
        mode: 0755
        content: |
          #! /usr/bin/bash
          artemis consumer --destination topic://wps.v1.result --message-count 99999999 --url tcp://10.5.0.7:61616 --user admin --password admin --verbose

    - name: Backup Producer
      copy:
        dest: /usr/local/bin/prodback
        mode: 0755
        content: |
          #! /usr/bin/bash
          artemis producer \
          --destination 'topic://wps.v1.result' \
          --default-port 5672
          --message-count 99999999 \
          --url 'tcp://10.5.0.4:5672' \
          --user admin \
          --password admin \
          --sleep 2000 \
          --message-size 32 \
          --verbose

    - name: Backup Consumer
      copy:
        dest: /usr/local/bin/conback
        mode: 0755
        content: |
          #! /usr/bin/bash
          artemis consumer --destination 'topic://wps.v1.result' --message-count 99999999 --url tcp://10.5.0.4:5672 --user admin --password admin --verbose





























    - name: Backup Producer
      copy:
        mode: 0755
        dest: /usr/local/bin/prodlive
        content: |
          #! /usr/bin/bash
          artemis producer \
          --destination 'topic://wps.v1.result' \
          --message-count 99999999 \
          --url 'tcp://10.5.0.3:5672' \
          --user admin \
          --password admin \
          --sleep 2000 \
          --message-size 32 \
          --non-persistent \
          --verbose


    - name: Live Consumer
      copy:
        dest: /usr/local/bin/conlive
        mode: 0755
        content: |
          #! /usr/bin/bash
          artemis consumer --destination 'topic://wps.v1.result' --message-count 99999999 --url tcp://10.5.0.3:5672 --user admin --password admin --verbose
