---
- name: Update All VMs
  hosts: default
  become: true
  remote_user: vagrant
  tasks:
    - name: Set authorized key taken from file
      authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', '.ssh/insecure_rsa.pub') }}"

    - name: Avoid vagrant trap with too many keys
      community.general.ini_file:
        path: /etc/ssh/sshd_config
        section:
        option: MaxAuthTries
        value: '50'
        backup: yes

    # Updating all packages is very slow
    - name: Upgrade all packages
      yum:
        name: '*'
        update_cache: yes
        state: latest

    - name: Add repository
      yum_repository:
        name: elastic
        description: Elasticsearch repository for 7.x packages
        baseurl: https://artifacts.elastic.co/packages/7.x/yum

    - name: Install java and packages
      yum:
        name:
          - avahi
          - avahi-tools
          - bzip2
          - epel-release
          - gcc
          - java-11-openjdk
          - java-11-openjdk-devel
          - kernel-devel
          - kernel-headers
          - make
          - mlocate
          - net-tools
          - perl
          - vim

    - name: Install Docker
      shell: |
        sudo yum install -y yum-utils
        sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        sudo yum install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
        sudo systemctl start docker


# Vagrant has been switching the hostname so they no longer match the box names
# NOTE: The VMs probably have to be restarted to get zero-conf to recognize their network names
# TODO: Look into restarting the zero-conf daemon as part of the hostname role.
- hosts: node1
  become: true
  remote_user: vagrant
  tasks:
    - name: 'hostanem for node1'
      import_role:
        name: hostname
      vars:
        hostnamex: 'node1'

- hosts: node2
  become: true
  remote_user: vagrant
  tasks:
    - name: 'hostname for node2'
      import_role:
        name: hostname
      vars:
        hostnamex: 'node2'

- name: Install Reflex
  hosts: default
  remote_user: vagrant
  become: true
  become_user: root
  tasks:
    - name: find
      find:
        paths: /vagrant
        patterns: "*.rpm"
      register: rpm_find

    # If there is no rpm file, the error message "The task includes an option with an undefined variable. The error was: list object has no element 0"
    - name: set fact
      set_fact:
        rpm_file: "{{ rpm_find.files[0].path }}"

    - name: Installing RPM file
      debug: msg="{{ rpm_file }}"

    - name: Install RPM
      yum:
        name: "{{ rpm_file }}"


## THE CONFIG-OPTIONS.SH LACKS THE PART THAT CREATES AND STARTS THE SERVICE. Could be missing other stuff too???
#- name: "Configure Node 1"
#  hosts: node1
#  become: true
#  remote_user: vagrant
#  tasks:
#    - name: Copy and Execute the Reflex config script
#      script: sudo setup-reflex.sh