- name: Install Artemis
  hosts: other
  become: true
  remote_user: vagrant
  tasks:
    - name: Create a symbolic link
      file:
        src: /home/vagrant/artemis/bin/artemis
        dest: /usr/local/bin/artemis
        state: link